/**
 * MobileNet(ImageNet) 영문 클래스명을 사용자에게 친숙한 한국어로 매핑.
 *
 * 1000개 전체 클래스 매핑 대신, 게이트가 자주 마주치는 일반 사물/식품/문구류
 * 위주로 정리한다. 매핑이 없으면 영문 첫 단어 묶음을 그대로 노출한다.
 */

const RAW_KO_LABELS: Record<string, string> = {
  "water bottle": "물병",
  "wine bottle": "와인병",
  "beer bottle": "맥주병",
  "pop bottle, soda bottle": "음료병",
  "pill bottle": "약병",
  "perfume, essence": "향수",
  "lotion": "로션",
  "soap dispenser": "디스펜서",
  "milk can": "우유캔",
  "beer can": "맥주캔",
  "tin can": "캔",
  "cup": "컵",
  "coffee mug": "머그컵",
  "measuring cup": "계량컵",
  "pitcher, ewer": "물주전자",
  "water jug": "물병",
  "bowl": "그릇",
  "mixing bowl": "믹싱볼",
  "soup bowl": "수프 그릇",
  "plate": "접시",
  "tray": "쟁반",
  "packet": "포장재",
  "envelope": "봉투",
  "carton": "종이상자",
  "crate": "상자",
  "shopping basket": "장바구니",
  "plastic bag": "비닐봉지",
  "shopping cart": "쇼핑카트",
  "vase": "꽃병",
  "candle, taper, wax light": "양초",
  "lighter, light, igniter, ignitor": "라이터",
  "fountain pen": "만년필",
  "ballpoint, ballpoint pen, ballpen, Biro": "볼펜",
  "rubber eraser, rubber, pencil eraser": "지우개",
  "lipstick, lip rouge": "립스틱",
  "matchstick": "성냥",
  "Band Aid": "밴드(반창고)",
  "syringe": "주사기",
  "thimble": "골무",
  "remote control, remote": "리모컨",
  "cellular telephone, cellular phone, cellphone, cell, mobile phone": "휴대폰",
  "iPod": "아이팟",
  "computer keyboard, keypad": "키보드",
  "mouse, computer mouse": "마우스",
  "modem": "모뎀",
  "hand-held computer, hand-held microcomputer": "휴대용 컴퓨터",
  "laptop, laptop computer": "노트북",
  "notebook, notebook computer": "노트북",
  "screwdriver": "드라이버",
  "hammer": "망치",
  "wrench, spanner": "스패너",
  "scissors": "가위",
  "safety pin": "옷핀",
  "nail": "못",
  "necklace": "목걸이",
  "ring, band": "반지",
  "wallet, billfold, notecase, pocketbook": "지갑",
  "purse": "지갑",
  "wig": "가발",
  "sunglasses, dark glasses, shades": "선글라스",
  "sunglass": "선글라스",
  "watch, ticker": "손목시계",
  "stopwatch, stop watch": "스톱워치",
  "digital watch": "디지털 시계",
  "analog clock": "아날로그 시계",
  "digital clock": "디지털 시계",
  "wall clock": "벽시계",
  "sock": "양말",
  "tie, neckwear": "넥타이",
  "Windsor tie": "넥타이",
  "bow tie, bow-tie, bowtie": "보타이",
  "jersey, T-shirt, tee shirt": "티셔츠",
  "sweatshirt": "스웨트셔츠",
  "cardigan": "카디건",
  "miniskirt, mini": "미니스커트",
  "swimming trunks, bathing trunks": "수영복",
  "orange": "오렌지",
  "lemon": "레몬",
  "banana": "바나나",
  "Granny Smith": "사과",
  "strawberry": "딸기",
  "pomegranate": "석류",
  "pineapple, ananas": "파인애플",
  "fig": "무화과",
  "bell pepper": "피망",
  "cucumber, cuke": "오이",
  "broccoli": "브로콜리",
  "cauliflower": "콜리플라워",
  "mushroom": "버섯",
  "head cabbage": "양배추",
  "artichoke, globe artichoke": "아티초크",
  "acorn": "도토리",
  "buckeye, horse chestnut, conker": "마로니에 열매",
  "corn": "옥수수",
  "ear, spike, capitulum": "이삭",
  "hip, rose hip, rosehip": "장미 열매",
  "menu": "메뉴판",
  "book jacket, dust cover, dust jacket, dust wrapper, dust sheet": "책 표지",
  "comic book": "만화책",
  "magazine": "잡지",
  "binder, ring-binder": "바인더",
  "spotlight, spot": "스포트라이트",
  "lampshade, lamp shade": "전등갓",
  "table lamp": "탁상 램프",
  "pot, flowerpot": "화분",
};

// 키를 일관되게 소문자로 정규화한다 — 조회 시점과 동일한 규칙 적용.
const KO_LABELS: Record<string, string> = Object.fromEntries(
  Object.entries(RAW_KO_LABELS).map(([k, v]) => [k.toLowerCase(), v]),
);

/** 영문 ImageNet 클래스명을 한국어 라벨로 매핑한다. 미정의 시 영문 첫 단어. */
export function toKoreanImagenetLabel(className: string): string {
  const key = className.toLowerCase();
  const exact = KO_LABELS[key];
  if (exact) return exact;
  // 콤마/공백 정리 후 첫 단어만 표시
  const head = className.split(",")[0]?.trim();
  return head || className;
}
